version: 2.1

orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@4.0
  aws-ecr: circleci/aws-ecr@9.0

jobs:
  build: # this can be any name you choose
    executor: python/default
    steps:
      - checkout  # Fetch your source code
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt # Install your project's dependencies
      - run:
          name: Build
          command: python main.py

  lint:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Linter
          command: |
            flake8

workflows:
  build-and-lint:
    jobs:
      - build
      - lint
      - aws-ecr/build-and-push-image:
          repo: monitorin-app
          tag: "latest,v1.0.0${CIRCLE_BUILD_NUM}"
          dockerfile: Dockerfile
          path: .
          requires:
            - build