version: 2.1

orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@4.0
  aws-ecr: circleci/aws-ecr@9.0

jobs:

  build-and-push:
    executor: aws-ecr/default
    steps:
      - checkout

      # Authenticate with AWS ECR using AWS credentials
      - aws-ecr/aws-auth:
          aws-access-key-id: $AWS_ACCESS_KEY_ID
          aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
          aws-region: us-east-1  # Replace with your AWS region

      # Build and push the Docker image to ECR
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t webapp .
            docker tag webapp:latest $AWS_ECR_REGISTRY_URL/webapp:latest
            docker push $AWS_ECR_REGISTRY_URL/webapp:latest

  build: # this can be any name you choose
    executor: python/default
    steps:
      - checkout  # Fetch your source code
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt # Install your project's dependencies
      - run:
          name: Build
          command: python main.py

  lint:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Linter
          command: |
            flake8

workflows:
  version: 2
  build-and-push:
    jobs:
      - build-and-push:
          aws-region: us-east-1 
      - build
      - lint