version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  build: # this can be any name you choose
    executor: python/default
    steps:
      - checkout  # Fetch your source code
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt # Install your project's dependencies
      - run:
          name: Build
          command: python app.py

  lint:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Linter
          command: |
            flake8

workflows:
  build-and-lint:
    jobs:
      - build
      - lint