apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-app-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mo-app
  template:
    metadata:
      labels:
        app: mo-app
    spec:
      containers:
      - name: mo-app
        image: webapp:1.1.0
        ports:
        - containerPort: 5000